import type { Presentation } from "./types";
export const dataJSON: Presentation = {
  title: "TestMaximalDataSet",
  slides: [
    {
      id: "0",
      background: { type: "color", color: "#6e750e" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 14,
          x: 0,
          y: 100,
          w: 50,
          h: 100,
          id: "0",
        },
        {
          type: "image",
          x: 100,
          y: 100,
          w: 400,
          h: 400,
          id: "1",
          src: "https://avatars.mds.yandex.net/i?id=cebb0526708bd75bfdb19f7aa52fe9459486bb4a-5291937-images-thumbs&n=13",
        },
        {
          type: "text",
          text: "Enter your text",
          font_size: 14,
          font_family: "Arial",
          x: 450,
          y: 500,
          w: 100,
          h: 100,
          id: "2",
        },
        {
          type: "text",
          text: "Enter your text",
          font_size: 14,
          font_family: "Arial",
          x: 400,
          y: 500,
          w: 100,
          h: 100,
          id: "3",
        },
        {
          type: "text",
          text: "Enter your text",
          font_size: 14,
          font_family: "Arial",
          x: 300,
          y: 500,
          w: 100,
          h: 100,
          id: "4",
        },
        {
          type: "image",
          x: 200,
          y: 500,
          w: 200,
          h: 500,
          id: "5",
          src: "https://habrastorage.org/webt/jw/x5/ue/jwx5uelv2ftie0oregurzbj1cqc.gif",
        },
      ],
    },
    {
      id: "1",
      background: {
        type: "image",
        src: "https://avatars.mds.yandex.net/i?id=605ad3dc45adebf385b090aa593e8b8a89aaaa91-5490649-images-thumbs&n=13",
      },
      slideObjects: [
        {
          type: "text",
          text: "Они уже близко",
          font_family: "Courier New",
          font_size: 56,
          x: 405.5,
          y: 227,
          w: 50,
          h: 100,
          id: "0",
        },
      ],
    },
    {
      id: "2",
      background: { color: "white", type: "color" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 96,
          x: 505.5,
          y: 427,
          w: 1000,
          h: 120,
          id: "0",
        },
        {
          type: "image",
          x: 405.5,
          y: 227,
          w: 250,
          h: 250,
          id: "2",
          src: "https://avatars.mds.yandex.net/i?id=f6e09bde2405237379ccaba3503e4203223ab0ff-6298174-images-thumbs&n=13",
        },
        {
          type: "image",
          x: 305.5,
          y: 127,
          w: 250,
          h: 250,
          id: "3",
          src: "https://main-cdn.sbermegamarket.ru/big1/hlr-system/-17/400/677/646/191/10/100055355046b0.png",
        },
      ],
    },
    {
      id: "3",
      background: { color: "white", type: "color" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 14,
          x: 0,
          y: 100,
          w: 50,
          h: 100,
          id: "0",
        },
      ],
    },
    {
      id: "4",
      background: { color: "white", type: "color" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 14,
          x: 0,
          y: 100,
          w: 50,
          h: 100,
          id: "0",
        },
      ],
    },
    {
      id: "5",
      background: { color: "white", type: "color" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 14,
          x: 0,
          y: 100,
          w: 50,
          h: 100,
          id: "0",
        },
      ],
    },
    {
      id: "6",
      background: { color: "white", type: "color" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 14,
          x: 0,
          y: 100,
          w: 50,
          h: 100,
          id: "0",
        },
      ],
    },
    {
      id: "7",
      background: { color: "white", type: "color" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 14,
          x: 0,
          y: 100,
          w: 50,
          h: 100,
          id: "0",
        },
      ],
    },
    {
      id: "8",
      background: { color: "white", type: "color" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 14,
          x: 0,
          y: 100,
          w: 50,
          h: 100,
          id: "0",
        },
      ],
    },
    {
      id: "9",
      background: { color: "white", type: "color" },
      slideObjects: [
        {
          type: "text",
          text: "Enter your text",
          font_family: "Courier New",
          font_size: 14,
          x: 0,
          y: 100,
          w: 50,
          h: 100,
          id: "0",
        },
      ],
    },
  ],
  selection: { selectedObjectID: [], selectedSlideID: ["1"] },
};
